__title__ = "insilicova"
__description__ = "Python implementation of the InSilicoVA Algorithm."
__url__ = "https://github.com/verbal-autopsy-software/pyinsilicova"
__version__ = "0.0.1"
__author__ = "Sherry Zhao, Jason Thomas"
__author_email__ = "zhao.3248@buckeyemail.osu.edu"
__license__ = "GPLv3"
