__title__ = "insilicova"
__description__ = "Python implementation of the InSilicoVA Algorithm."
__url__ = "https://github.com/verbal-autopsy-software/pyinsilicova"
__version__ = "0.0.2"
__author__ = "Jason Thomas & Sherry Zhao"
__author_email__ = "jarathomas@gmail.com"
__license__ = "GPLv3"
